version: '3.8'

services:
  train:
    build:
      context: ..
      dockerfile: train/Dockerfile
    container_name: train
    volumes:
      - /mnt/object:/mnt/object
    networks:
      - mlops-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://129.114.25.37:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=hrwbqzUS85G253yKi43T
      - AWS_DEFAULT_REGION=us-east-1
    # 默认命令，可以通过 docker-compose run 覆盖
    command: echo "Please specify training task"

networks:
  mlops-network:
    external: true 